import type { Animal, Provider, User } from "./types";

// Static hashed password for "Password123!" to keep seed-data client-safe without node:crypto bundling
const DEFAULT_PASSWORD_HASH =
  "a1b2c3d4e5f60718293a4b5c6d7e8f90:39db16b7a872a4ec181634e45877088ca1af88894e8ec3434b3fa8a056c6a737d7956e3ed13047e3525f909d4c79866f87a29f847b4e9d8ae915cddef1d7c9ee";

export const users: User[] = [
  {
    id: "user-pet-parent",
    name: "Aisha Gupta",
    email: "aisha@animalcare.app",
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: "PET_PARENT",
    city: "Delhi",
    phone: "+91 98765 43210",
  },
  {
    id: "user-rescuer",
    name: "Rohan Verma",
    email: "rohan@animalcare.app",
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: "RESCUER",
    city: "Bengaluru",
    phone: "+91 98111 22334",
  },
  {
    id: "provider-vet",
    name: "Dr. Meera Nair",
    email: "provider@animalcare.app",
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: "PROVIDER",
    city: "Mumbai",
    phone: "+91 91234 56789",
  },
  {
    id: "admin-user",
    name: "Admin Team",
    email: "admin@animalcare.app",
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: "ADMIN",
    city: "Hyderabad",
    phone: "+91 90000 11122",
  },
];


export const animals: Animal[] = [
  {
    id: "animal-bruno",
    name: "Bruno",
    species: "Dog",
    breed: "Golden Retriever",
    age: "4 years",
    ownerId: "user-pet-parent",
  },
  {
    id: "animal-milo",
    name: "Milo",
    species: "Cat",
    breed: "Persian",
    age: "2 years",
    ownerId: "user-pet-parent",
  },
];

export const providers: Provider[] = [
  {
    id: "provider-1",
    name: "Paws & Claws Vet Hospital",
    type: "veterinary_clinic",
    city: "Delhi",
    address: "Plot 18, Saket, New Delhi",
    phone: "+91 11 4555 2200",
    verified: true,
    status: "open",
    emergencyAvailable: true,
    description: "Full-service veterinary clinic for dogs, cats, and small animals.",
    animalsTreated: ["Dog", "Cat", "Rabbit"],
    services: ["Vaccination", "Diagnostics", "Dental Care"],
    operatingHours: [
      { day: "Mon", open: "09:00", close: "20:00" },
      { day: "Tue", open: "09:00", close: "20:00" },
      { day: "Wed", open: "09:00", close: "20:00" },
      { day: "Thu", open: "09:00", close: "20:00" },
      { day: "Fri", open: "09:00", close: "20:00" },
      { day: "Sat", open: "10:00", close: "18:00" },
    ],
    coordinates: { lat: 28.5244, lng: 77.2063 },
    rating: 4.8,
    reviews: 420,
  },
  {
    id: "provider-2",
    name: "Pet Rescue 24/7",
    type: "emergency_vet",
    city: "Delhi",
    address: "Near Gurugram Sector 29, Delhi NCR",
    phone: "+91 98 7643 1100",
    verified: true,
    status: "open",
    emergencyAvailable: true,
    description: "Emergency support and urgent intervention for critical animal distress.",
    animalsTreated: ["Dog", "Cat", "Bird"],
    services: ["Emergency triage", "Critical care"],
    operatingHours: [
      { day: "Mon", open: "00:00", close: "23:59" },
      { day: "Tue", open: "00:00", close: "23:59" },
      { day: "Wed", open: "00:00", close: "23:59" },
      { day: "Thu", open: "00:00", close: "23:59" },
      { day: "Fri", open: "00:00", close: "23:59" },
      { day: "Sat", open: "00:00", close: "23:59" },
      { day: "Sun", open: "00:00", close: "23:59" },
    ],
    coordinates: { lat: 28.49, lng: 77.09 },
    rating: 4.7,
    reviews: 290,
  },
  {
    id: "provider-3",
    name: "SafePaw Ambulance Network",
    type: "animal_ambulance",
    city: "Mumbai",
    address: "Andheri East, Mumbai",
    phone: "+91 22 6622 9044",
    verified: true,
    status: "open",
    emergencyAvailable: true,
    description: "Animal transport service for emergencies and scheduled referrals.",
    animalsTreated: ["Dog", "Cat", "Cow"],
    services: ["Transport", "Pickup service"],
    operatingHours: [
      { day: "Mon", open: "08:00", close: "22:00" },
      { day: "Tue", open: "08:00", close: "22:00" },
      { day: "Wed", open: "08:00", close: "22:00" },
      { day: "Thu", open: "08:00", close: "22:00" },
      { day: "Fri", open: "08:00", close: "22:00" },
      { day: "Sat", open: "09:00", close: "21:00" },
    ],
    coordinates: { lat: 19.1136, lng: 72.8697 },
    rating: 4.5,
    reviews: 154,
  },
  {
    id: "provider-4",
    name: "Bengaluru Animal Rescue Alliance",
    type: "ngo",
    city: "Bengaluru",
    address: "Whitefield, Bengaluru",
    phone: "+91 80 4444 1111",
    verified: true,
    status: "open",
    emergencyAvailable: false,
    description: "NGO helping injured, abandoned, and rescued animals find care and safe placement.",
    animalsTreated: ["Dog", "Cat", "Stray animals"],
    services: ["Rescue coordination", "Community care"],
    operatingHours: [
      { day: "Mon", open: "10:00", close: "18:00" },
      { day: "Tue", open: "10:00", close: "18:00" },
      { day: "Wed", open: "10:00", close: "18:00" },
      { day: "Thu", open: "10:00", close: "18:00" },
      { day: "Fri", open: "10:00", close: "18:00" },
    ],
    coordinates: { lat: 12.9716, lng: 77.5946 },
    rating: 4.6,
    reviews: 188,
  },
  {
    id: "provider-5",
    name: "Himalaya Companion Care",
    type: "boarding",
    city: "Chandigarh",
    address: "Sector 35C, Chandigarh",
    phone: "+91 172 244 9090",
    verified: true,
    status: "closed",
    emergencyAvailable: false,
    description: "Boarding and pet care with supervised play and routine monitoring.",
    animalsTreated: ["Dog", "Cat"],
    services: ["Boarding", "Day-care"],
    operatingHours: [
      { day: "Mon", open: "08:30", close: "19:00" },
      { day: "Tue", open: "08:30", close: "19:00" },
      { day: "Wed", open: "08:30", close: "19:00" },
      { day: "Thu", open: "08:30", close: "19:00" },
      { day: "Fri", open: "08:30", close: "19:00" },
      { day: "Sat", open: "09:00", close: "17:00" },
    ],
    coordinates: { lat: 30.7333, lng: 76.7794 },
    rating: 4.4,
    reviews: 98,
  },
  {
    id: "provider-6",
    name: "City Pet Rescue Squad",
    type: "rescuer",
    city: "Hyderabad",
    address: "Madhapur, Hyderabad",
    phone: "+91 40 2920 1888",
    verified: false,
    status: "open",
    emergencyAvailable: true,
    description: "Rescue volunteers who help with stray animals, injuries, and urgent transport.",
    animalsTreated: ["Dog", "Cat", "Stray animals"],
    services: ["Rescue support", "Rapid pickup"],
    operatingHours: [
      { day: "Mon", open: "09:00", close: "18:00" },
      { day: "Tue", open: "09:00", close: "18:00" },
      { day: "Wed", open: "09:00", close: "18:00" },
      { day: "Thu", open: "09:00", close: "18:00" },
      { day: "Fri", open: "09:00", close: "18:00" },
    ],
    coordinates: { lat: 17.385, lng: 78.4867 },
    rating: 4.2,
    reviews: 66,
  },
];

export const featuredProviders = providers.slice(0, 3);
